# Generated by Django 6.0.5 on 2026-08-19 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('농촌일손', '농촌일손'), ('주택수리', '주택수리'), ('돌봄', '돌봄'), ('동아리', '동아리'), ('기타', '기타')], max_length=20)),
                ('region', models.CharField(blank=True, choices=[('옥천읍', '옥천읍'), ('동이면', '동이면'), ('안남면', '안남면'), ('청성면', '청성면'), ('청산면', '청산면'), ('이원면', '이원면'), ('군서면', '군서면'), ('군북면', '군북면')], max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recruit_count', models.IntegerField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_posts',
                'indexes': [models.Index(fields=['category'], name='job_posts_categor_cbe752_idx'), models.Index(fields=['region'], name='job_posts_region_ad4050_idx')],
            },
        ),
    ]
