# Generated by Django 6.0.5 on 2026-08-19 15:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, choices=[('옥천읍', '옥천읍'), ('동이면', '동이면'), ('안남면', '안남면'), ('청성면', '청성면'), ('청산면', '청산면'), ('이원면', '이원면'), ('군서면', '군서면'), ('군북면', '군북면')], max_length=10)),
                ('detail_address', models.TextField()),
                ('room_type', models.CharField(choices=[('원룸', '원룸'), ('투룸이상', '투룸이상'), ('오피스텔', '오피스텔'), ('주택', '주택'), ('기타', '기타')], max_length=10)),
                ('room_layout', models.CharField(blank=True, max_length=100)),
                ('size_pyeong', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('deal_type', models.CharField(choices=[('전세', '전세'), ('월세', '월세')], max_length=10)),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('monthly_rent', models.IntegerField(blank=True, null=True)),
                ('maintenance_fee', models.IntegerField(blank=True, null=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'housing_posts',
            },
        ),
        migrations.CreateModel(
            name='HousingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='housing_photos/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('housing_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='board.housingpost')),
            ],
            options={
                'db_table': 'housing_photos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='housingpost',
            index=models.Index(fields=['room_type'], name='housing_pos_room_ty_8ff93d_idx'),
        ),
        migrations.AddIndex(
            model_name='housingpost',
            index=models.Index(fields=['region'], name='housing_pos_region_b4bf87_idx'),
        ),
    ]
