# Generated by Django 6.0.5 on 2026-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
    ]
