# Generated by Django 6.0.5 on 2026-05-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('신청예정', 'Pending'), ('신청완료', 'Applied'), ('관심없음', 'Not Interested')], default='신청예정', max_length=10)),
                ('d7_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_policies', to='users.userprofile')),
            ],
            options={
                'db_table': 'user_policies',
                'unique_together': {('profile', 'policy')},
            },
        ),
    ]
