# Generated by Django 6.0.5 on 2026-05-29 05:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_userpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='checked_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
