# Generated by Django 6.0.5 on 2026-06-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpolicy_checked_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='education_hours',
        ),
    ]
