# Generated by Django 6.0.5 on 2026-06-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_education_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prev_residence_type',
            field=models.CharField(blank=True, choices=[('동', '동'), ('읍면', '읍/면')], max_length=10),
        ),
    ]
