# Generated by Django 6.0.5 on 2026-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_prev_residence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prev_residence_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prev_residence_is_rural',
            field=models.BooleanField(null=True),
        ),
    ]
