# Generated by Django 6.0.5 on 2026-08-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_prev_residence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='applicant_name',
            field=models.TextField(blank=True),
        ),
    ]
