# Generated by Django 6.0.5 on 2026-05-20 07:06

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('지원금사용처', '지원금사용처'), ('농자재', '농자재'), ('농기계', '농기계'), ('농협', '농협'), ('행정', '행정'), ('생활', '생활')], max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('subsidy_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('receipt_claimable', models.BooleanField(default=False)),
                ('local_memo', models.TextField(blank=True)),
                ('price_notes', models.TextField(blank=True)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'local_places',
                'indexes': [models.Index(fields=['category'], name='local_place_categor_3b45a3_idx'), django.contrib.postgres.indexes.GinIndex(fields=['subsidy_tags'], name='idx_places_subsidy_tags')],
            },
        ),
    ]
