# Generated by Django 6.0.5 on 2026-06-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localplace',
            name='category',
            field=models.CharField(choices=[('지원금사용처', '지원금사용처'), ('농자재', '농자재'), ('농기계', '농기계'), ('농협', '농협'), ('행정', '행정'), ('생활', '생활'), ('음식점', '음식점'), ('약국', '약국'), ('건축자재', '건축자재'), ('의류', '의류'), ('식품', '식품'), ('전자제품', '전자제품'), ('가구', '가구')], max_length=20),
        ),
    ]
