# Generated by Django 6.0.5 on 2026-08-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_localplace_business_hours_localplace_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localplace',
            name='counseling_center_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localplace',
            name='okcheon_news_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localplace',
            name='category',
            field=models.CharField(choices=[('지원금사용처', '지원금사용처'), ('농자재', '농자재'), ('농기계', '농기계'), ('농협', '농협'), ('행정', '행정'), ('생활', '생활'), ('음식점', '음식점'), ('약국', '약국'), ('건축자재', '건축자재'), ('의류', '의류'), ('식품', '식품'), ('전자제품', '전자제품'), ('가구', '가구'), ('동호회', '동호회')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlaceEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='places.localplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_endorsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'place_endorsements',
                'unique_together': {('place', 'user')},
            },
        ),
    ]
