# Generated by Django 6.0.5 on 2026-08-26 11:02

from django.db import migrations, models


REMAP = {
    '건축자재': '부동산',
    '약국': '생활',
    '지원금사용처': '생활',
    '농협': '생활',
    '의류': '생활',
    '식품': '생활',
    '전자제품': '생활',
    '가구': '생활',
}

RECLASSIFY_TO_LANDMARK = [97, 98, 99]  # 옥천향수시네마 / 옥천체육센터 / 옥천문화예술관


def remap_categories(apps, schema_editor):
    LocalPlace = apps.get_model('places', 'LocalPlace')
    for old, new in REMAP.items():
        LocalPlace.objects.filter(category=old).update(category=new)
    LocalPlace.objects.filter(pk__in=RECLASSIFY_TO_LANDMARK).update(category='명소')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_localplace_counseling_center_recommended_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_categories, noop),
        migrations.AlterField(
            model_name='localplace',
            name='category',
            field=models.CharField(choices=[('농자재', '농자재'), ('농기계', '농기계'), ('행정', '행정'), ('생활', '생활'), ('명소', '명소'), ('음식점', '음식점'), ('동호회', '동호회'), ('부동산', '부동산')], max_length=20),
        ),
    ]
