# Generated by Django 6.0.5 on 2026-05-20 07:06

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('benefit_type', models.CharField(blank=True, choices=[('현금지원', '현금지원'), ('교육', '교육'), ('컨설팅', '컨설팅'), ('시설', '시설'), ('세금감면', '세금감면'), ('현물', '현물'), ('기타', '기타')], max_length=20)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_text', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('복지로', '복지로'), ('수동입력', '수동입력'), ('귀농센터', '귀농센터')], default='수동입력', max_length=20)),
                ('min_age', models.SmallIntegerField(default=0)),
                ('max_age', models.SmallIntegerField(default=130)),
                ('gender', models.CharField(default='all', max_length=10)),
                ('region_codes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('occupation_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('household_type', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('move_status', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('income_level', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('disability_required', models.BooleanField(null=True)),
                ('condition_tree', models.JSONField(blank=True, null=True)),
                ('apply_start_date', models.DateField(blank=True, null=True)),
                ('apply_end_date', models.DateField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True)),
                ('managing_org', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policies',
                'indexes': [models.Index(fields=['min_age', 'max_age'], name='policies_min_age_c2b186_idx'), models.Index(fields=['apply_end_date'], name='policies_apply_e_734b70_idx'), django.contrib.postgres.indexes.GinIndex(fields=['region_codes'], name='idx_policies_region_codes'), django.contrib.postgres.indexes.GinIndex(fields=['occupation_tags'], name='idx_policies_occupation_tags'), django.contrib.postgres.indexes.GinIndex(fields=['income_level'], name='idx_policies_income_level')],
            },
        ),
    ]
