# Generated by Django 6.0.5 on 2026-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
