# Generated by Django 6.0.5 on 2026-05-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_add_raw_text_to_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='policies.policy')),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['order'],
            },
        ),
    ]
