# Generated by Django 6.0.5 on 2026-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
