# Generated by Django 6.0.5 on 2026-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_policy_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='source',
            field=models.CharField(choices=[('복지로', '복지로'), ('수동입력', '수동입력'), ('귀농센터', '귀농센터'), ('옥천군청', '옥천군청')], default='수동입력', max_length=20),
        ),
    ]
