# Generated by Django 6.0.5 on 2026-08-30 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_logs',
                'indexes': [models.Index(fields=['created_at'], name='request_log_created_4f2782_idx'), models.Index(fields=['path'], name='request_log_path_5a9834_idx')],
            },
        ),
    ]
